# Generated by Django 2.1.8 on 2019-10-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='map_lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='post',
            name='map_lon',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(upload_to='api_v1/images/'),
        ),
    ]
