# Generated by Django 2.1.8 on 2019-10-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20191020_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='map_lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='post',
            name='map_lon',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='経度'),
        ),
    ]
